model_params:
  name: 'BetaTCVAE'
  in_channels: 1
  latent_dim: 10
  anneal_steps: 10000
  alpha: 1.
  beta:  6.
  gamma: 1.

exp_params:
  dataset: "satellite_hill"
  data_path: "../../Share_Data/satellite/jpg_hill_d10_rv/"
  #dataset: "satellite_rgb"
  #data_path: "../../Share_Data/satellite/jpg_rgb_all_d10/"
  test_ratio: 0.2
  img_size: 64
  batch_size: 144 # Better to have a square number
  LR: 0.001
  weight_decay: 0.0
#  scheduler_gamma: 0.99

trainer_params:
  gpus: 1
  max_epochs: 500

logging_params:
  save_dir: "logs/"
  name: "BetaTCVAE"
  manual_seed: 1265
