model_params:
  name: 'VQVAE'
  in_channels: 1
  embedding_dim: 64
  num_embeddings: 512
  img_size: 64
  beta: 0.25

exp_params:
  dataset: "satellite_hill"
  data_path: "../../Share_Data/satellite/jpg_hill_rv_d10/"
  img_size: 64
  test_ratio: 0.2
  batch_size: 144 # Better to have a square number
  LR: 0.001
  weight_decay: 0.0
  scheduler_gamma: 0.0

trainer_params:
  gpus: 1
  max_epochs: 500

logging_params:
  save_dir: "logs/"
  name: "VQVAE"
  manual_seed: 1265
